import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import { Sidebar } from "./components/ui/Sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-bl from-[#000238] via-[#000238] via-[#1c0018] to-[#140405] min-h-screen">
        <Sidebar>
          {children}
        </Sidebar>
      </body>
    </html>
  );
}
